### ISSUE TITLE
Allow for custom json.dumps encoders, just like it was possible in 

### ISSUE THREAD

**Issue by trickkiste** [IBM/cloudant-python-sdk#335]
In python-cloudant it was possible to set a custom encoder for the json.dumps part of the library, so one e.g. could enable the library to deal with variables of type Decimal.

```
:param str encoder: Optional json Encoder object used to encode
        documents for storage.  Defaults to json.JSONEncoder.
```

Currently that is not possible in cloudant-python-sdk, which makes it much harder to use this library for e.g. accounting applications.

Please add this feature.

**Comment by tomblench** [comment]
Hi @trickkiste, for these kinds of use cases we provide [Raw IO](https://github.com/IBM/cloudant-python-sdk#raw-io) which allows users to fully control serialisation and deserialisation.

As stated in the link above, if you need a custom encoder, APIs like [post_document](https://ibm.github.io/cloudant-python-sdk/docs/0.2.1/ibmcloudant.html#ibmcloudant.cloudant_v1.CloudantV1.post_document) can also take a `BinaryIO` object instead of a `Document`.

Here is a sample showing how to use it with a custom JSON encoder for complex numbers (adapted from the python reference):
```python
import json

from ibm_cloud_sdk_core import ApiException
from ibmcloudant.cloudant_v1 import CloudantV1, Document
from io import StringIO

class ComplexEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, complex):
            return [obj.real, obj.imag]
        # Let the base class default method raise the TypeError
        return json.JSONEncoder.default(self, obj)

io = StringIO()
client = CloudantV1.new_instance()

example_db_name = "python_test"
example_doc_id = "doc3"

json.dump({"_id": example_doc_id,
           "complex_number": 2 + 1j},
          io,
          cls=ComplexEncoder)

update_document_response = client.post_document(
    db=example_db_name,
    document=io.getvalue(),
    headers={"content-type":"application/json"}
).get_result()
```
