### ISSUE TITLE
ChunkEncodingError

### ISSUE THREAD

**Issue by tontech** [IBM/cloudant-python-sdk#376]
**Describe the bug**

Got chunkencoding error when the calling post_partition_find with limit 200
**To Reproduce**

calling post_partition_find when database got bigger
**Expected behavior**

**Screenshots**

   response = self.send(request, **kwargs)
  File "/home/tonio/tm/thepack/fastapi/main/virtualenv/lib/python3.9/site-packages/ibm_cloud_sdk_core/base_service.py", line 308, in send
    response = self.http_client.request(**request,
  File "/home/tonio/tm/thepack/fastapi/main/virtualenv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tonio/tm/thepack/fastapi/main/virtualenv/lib/python3.9/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/home/tonio/tm/thepack/fastapi/main/virtualenv/lib/python3.9/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/home/tonio/tm/thepack/fastapi/main/virtualenv/lib/python3.9/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Must gather (please complete the following information):**
 - SDK Version [e.g. 1.2.1]
 - Python Version [e.g. Python 3.7]
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)
Python3.9
ibmcloudant 0.3.1

**Additional context**

**Comment by eiri** [comment]
It seems that you've got an empty response from the server. You can try to tweak [automatic retries](https://github.com/IBM/ibm-cloud-sdk-common#automatic-retries) option if that's an intermittent issue or tune [timeouts](https://github.com/IBM/ibm-cloud-sdk-common#configuring-request-timeouts) to alleviate that.

For troubleshooting try to access the end-point `POST /{db}/_partition/{partition_key}/_find` with `curl` with your query to see what is the response you are getting from your server. A guess would be that since you've mentioned your database has grown your are facing a timeout on not optimized index. Try to run `POST /{db}/_partition/{partition_id}/_explain` and see if you can improve your query.

**Comment by rnewson** [comment]
We've submitted a pull request upstream to provide a better error message in this case: https://github.com/urllib3/urllib3/pull/2860

**Comment by ricellis** [comment]
Closing as stale, let us know if you have more problems with this.
