### ISSUE TITLE
"id" field in document gets removed when creating a document

### ISSUE THREAD

**Issue by slenin** [IBM/cloudant-python-sdk#490]
**Describe the bug**
When a document has both "_id" and "id" field, the "id" field is removed. However, I am able to have a document with both fields when created through the Cloudant dashboard.

**To Reproduce**
sample_document = {
        "_id": "70b63682-b93a-4c77-aad2-65501347265f4",
        "id": "1",
        "name": "Yamba",
        "quantity": 10.5,
        "sale": False,
    }
document: Document = Document.from_dict(sample_document)
client.post_document(
    db="testdb",
    document=document
).get_result()

Document in the store is
{
  "_id": "70b63682-b93a-4c77-aad2-65501347265f4",
  "_rev": "1-d5a833fdf112ec7c7d85dde1cbed7878",
  "name": "Yamba",
  "quantity": 10.5,
  "sale": false
}

Document.from_dict seems to remove the "id" field. Are there any workarounds to keep both fields?

**Expected behavior**
The document in the store should be
{
  "_id": "70b63682-b93a-4c77-aad2-65501347265f4",
  "_rev": "1-d5a833fdf112ec7c7d85dde1cbed7878",
  "id": "1",
  "name": "Yamba",
  "quantity": 10.5,
  "sale": false
}

**Must gather (please complete the following information):**
 - SDK Version 0.4.2
 - Python 3.11
 - IBM Cloudant
 - post_document

**Comment by slenin** [comment]
Using BinaryIO has expected behavior

sample_document = {
    "_id": "70b63682-b93a-4c77-aad2-65501347265f4",
    "id": "1",
    "name": "Yamba",
    "quantity": 10.5,
    "sale": False,
}

docbytes = json.dumps(sample_document).encode('utf-8')
response = client.post_document(
    db="testdb",
    document=docbytes,
    content_type='application/json'
).get_result()

**Comment by ricellis** [comment]
The internal representation of the `Document` model does not allow for fields with the same names as the reserved (`_` prefixed) document fields. Sorry that does not appear to be documented, I think it should be listed in our `KNOWN_ISSUES` and I'll look to get that fixed.

As you have already discovered one workaround is to use binary IO, which is the means by which the SDK allows for more flexible user-controlled serialization and deserialization. The other potential workarounds are to use a different name for the field (e.g. `product_id` or to embed the `id` in a nested object e.g. `"data": {"id": 1, "name": …}`.

As a note of caution the CouchDB and Cloudant APIs do sometimes return the `_id` in a field called `id` (e.g. in the response after writing a document or in view and query responses). So having fields called both `_id`  and `id` may make an application hard to understand since `['id']` in one context could refer to something completely different than `['id']` in a different context.

**Comment by ricellis** [comment]
This limitation is now documented at https://github.com/IBM/cloudant-python-sdk/blob/main/KNOWN_ISSUES.md#name-collisions-with-reserved-metadata-fields

**Comment by ricellis** [comment]
This problem has been resolved in version [`0.8.0`](https://github.com/IBM/cloudant-python-sdk/releases/tag/v0.8.0). From that version it is possible to have both `_id` and `id` properties in the same `Document`.
