### ISSUE TITLE
Providing Authentificator in CloudantV1 init does not work

### ISSUE THREAD

**Issue by NielsKorschinsky** [IBM/cloudant-python-sdk#525]
**Describe the bug**

I am trying to init the Client using the programmatic approach.
When using `CloudantV1(authenticator=authenticator).new_instance()`, the provided authenticator is ignored. 
It is not throwing an error, but when accessing the data afterward it is trying to use the default authentificator.

**To Reproduce**

1. Create an authenticator, validate it

```python
basic_authenticator = BasicAuthenticator(
    username=self.__cloudant_config.cloudant_api_key,
    password=self.__cloudant_config.cloudant_secret
)
basic_authenticator.validate()
```

2. Use the authenticator to create a new instance, use a different service URL. DO NOT provide ENV credentials

```python
self.__client: CloudantV1 = CloudantV1(authenticator=basic_authenticator).new_instance()
self.__client.set_service_url(self.__cloudant_config.cloudant_url)
```

3. Query anything to see the failure

```python
test = self.__client.post_view_queries(...)
```

Error message:
```
Exception has occurred: ApiException
Error: Provided API key could not be found., Code: 400
```

4. After Step 2, you may get authentificator to validate the issue

```python
test = self.__client.get_authenticator()
```
This will NOT have the fields `authorization_header`, `username`, and `password` as the provided `basic_authenticator` has.

**Expected behavior**

When setting the authenticator in the init, it should be equally as setting it afterward via instance variable access. 
The Step 2 should work.

**Screenshots**

<img width="362" alt="image" src="https://github.com/IBM/cloudant-python-sdk/assets/49568673/b1820838-e4bc-4d92-9750-e2a8991a3f8d">

<img width="801" alt="image" src="https://github.com/IBM/cloudant-python-sdk/assets/49568673/d10cf7cc-9a2c-4fcc-8033-e8feff1ae1a8">

Please see that `test` is also a `IAMAuthenticator` instead.

<img width="521" alt="image" src="https://github.com/IBM/cloudant-python-sdk/assets/49568673/7d971d1b-4c16-4a06-bf38-c9df53641ac4">

**Must gather (please complete the following information):**
 - SDK Version [e.g. 1.2.1]
 ```
ibm-cloud-sdk-core==3.16.7  # via ibmcloudant
ibmcloudant==0.4.4        # via -r requirements.in
```
 - Python Version: Python3.9
 - Name of service that you're trying to use (if applicable): CloudantV1
 - Name of operation that you're trying to invoke: Initalize of CloudantV1

**Additional context**

Workaround:

Step 2, replace with following code

```python
self.__client: CloudantV1 = CloudantV1.new_instance()
self.__client.authenticator = basic_authenticator
self.__client.set_service_url(self.__cloudant_config.cloudant_url)
```

**Comment by mojito317** [comment]
Hi @NielsKorschinsky, thanks for the report!

As far as I know, none of the provided documentation is using the `new_instance` call for programmatic authentication. According to our [API Documentation](https://test.cloud.ibm.com/apidocs/cloudant?code=python#programmatic-authentication) and the [Core documentation](https://github.com/IBM/python-sdk-core/blob/main/Authentication.md#basic-authentication) your code should look like this:

```py
from ibmcloudant.cloudant_v1 import CloudantV1
from ibm_cloud_sdk_core.authenticators import BasicAuthenticator

...
basic_authenticator = BasicAuthenticator(
    username=self.__cloudant_config.cloudant_api_key,
    password=self.__cloudant_config.cloudant_secret
)

self.__client: CloudantV1 = CloudantV1(authenticator=authenticator)

self.__client.set_service_url(self.__cloudant_config.cloudant_url)
```

`new_instance` is used when a service is set externally by a config file or environment variables, with the help of a service name variable, which is by default `CLOUDANT`. So in your case, this happened:
1. create a basic authenticator
2. use it as your client's authenticator
3. override those auth creds immediately with the `new_instance()` call which by default uses IAM, and look for an IAM API key under the `CLOUDANT_APIKEY` env var/config var which is presumably unset
4. set the URL for your service

Your workaround works because you swapped the order:
1. create an instance with the `new_instance()` call
2. override the default settings with your programmatic settings
3.  set the URL for your service

**Comment by NielsKorschinsky** [comment]
Ah, thanks! So I should not be using the `new_instance()` call and all should be fine.

Can you might change the programmatic approach to issue a warning, if using the `new_instance` method on a object, instead of a class? Or do you know any way to make this a bit clearer to the user?
