### ISSUE TITLE
URL formatted incorrectly leading to "session request failed" error

### ISSUE THREAD

**Issue by raunakkbanerjee** [IBM/cloudant-python-sdk#600]
My question: Why does `http://@couchdb_prod:5984/_session` get formatted as `http://ouchdb_prod:5984/_session`? An issue with the "@" symbol? This leads to a "session request failed" error due to the invalid url

I am trying to set up a replication between two couchdb instances which I have created using docker compose. I have created a database on one of them and want it to be replicated on the other. The url for the two databases are: `http://@couchdb_prod:5984/dummy_prod` and `http://@couchdb_dev:5985/dummy_dev`

```
import time
from ibmcloudant.cloudant_v1 import CloudantV1, ReplicationDocument, ReplicationDatabase, ReplicationDatabaseAuth, ReplicationDatabaseAuthBasic
from ibmcloudant import CouchDbSessionAuthenticator

username = "admins"
password = "password"

service_client = CloudantV1(CouchDbSessionAuthenticator(username, password))
service_client.set_service_url(r'http://@couchdb_dev:5985/')

source_auth_iam = ReplicationDatabaseAuthBasic(
  username=username,
  password=password
)
source_auth = ReplicationDatabaseAuth(
  basic=source_auth_iam
)

source_db = ReplicationDatabase(
  auth=source_auth,
  url=r'http://@couchdb_prod:5984/dummy_prod',
)

target_auth_iam = ReplicationDatabaseAuthBasic(
  username=username,
  password=password
)
target_auth = ReplicationDatabaseAuth(
  basic=target_auth_iam
)
target_db = ReplicationDatabase(
  auth=target_auth,
  url=r'http://@couchdb_dev:5985/dummy_dev',
)

id = "repldoc"

replication_document = ReplicationDocument(
  continuous=True,
  id=id,
  create_target=True,
  source=source_db,
  target=target_db
)

response = service_client.put_replication_document(
  doc_id=id,
  replication_document=replication_document
).get_result()


print(response)

while True:
    time.sleep(10)
    response = service_client.get_scheduler_document(doc_id=id).get_result()
    print(response)
```

`service_client.put_replication_document` starts the replication and I have `service_client.get_scheduler_document` to check on the replication status.

The issue is that the replication keeps crashing, with the following response from `service_client.get_scheduler_document`

```
{'database': '_replicator', 'doc_id': 'repldoc', 'id': '85dbcbf5d94f76f6aa0e8e689792a174+continuous+create_target', 'node': 'nonode@nohost', 'source': 'http://@couchdb_prod:5984/dummy_prod/', 'target': 'http://@couchdb_dev:5985/dummy_dev/', 'state': 'crashing', 'info': {'error': '{replication_auth_error,\n    {session_request_failed,"http://ouchdb_prod:5984/_session",[],\n   
     {conn_failed,{error,nxdomain}}}}'}, 'error_count': 5, 'last_updated': '2024-01-19T09:51:53Z', 'start_time': '2024-01-19T09:39:54Z', 'source_proxy': None, 'target_proxy': None}
```
Key thing is that it says `session_request_failed` and the url says `http://ouchdb_prod:5984/_session` 

Why does `http://@couchdb_prod:5984/_session` get formatted as `http://ouchdb_prod:5984/_session`? An issue with the "@" symbol?

I am using a python 3.10 slim image

**Comment by ricellis** [comment]
From your sample it appears that `cloudant-python-sdk` is working fine as it appears to have been able to connect successfully and write the replication document.
The handling of the content of the replication document to actually do replications is inside CouchDB.

It is worth pointing out though that `@` is a URI [reserved character](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) - in the case of `cloudant-python-sdk` the URL `http://@couchdb_dev:5985/` is likely treated by the underlying Python URL handling as as `http://couchdb_dev:5985/` (with disregarded balnk user information) because `@` is the URL separator for user information (i.e. http://user:pass@url`).

If you _really_ want to use `@` in a URL you should percent encode it i.e. `http://%40couchdb_dev`, but AFAIK that is not a valid hostname and I would advise against attempting to use `@` in a hostname as it violates the [preferred name syntax](https://datatracker.ietf.org/doc/html/rfc1034#section-3.5).

IIRC docker compose uses the service name from the yaml as the network host name and I'm pretty sure those are restricted to `[a-zA-Z0-9_.-]`. If your service name is `couchdb_prod` then the URL to use `http://couchdb_prod:5984`.

**Comment by raunakkbanerjee** [comment]
Without the `@`, I get the following from `service_client.get_scheduler_document`
```
{'database': '_replicator', 'doc_id': 'repldoc', 'id': '4235fbd237a7767a0fb43a7695c655a2+continuous+create_target', 'node': 'nonode@nohost', 'source': 'http://couchdb_prod:5984/dummy_prod/', 'target': 'http://couchdb_dev:5985/dummy_dev/', 'state': 'crashing', 'info': {'error': 'unauthorized: unauthorized to access or create database http://couchdb_prod:5984/dummy_prod/'}, 'error_count': 1, 'last_updated': '2024-01-19T16:32:45Z', 'start_time': '2024-01-19T16:32:43Z', 'source_proxy': None, 'target_proxy': None}
```

Basically it says `{'error': 'unauthorized: unauthorized to access or create database http://couchdb_prod:5984/dummy_prod/'}`.
`@` seems to be necessary for this. Any suggestions for ways to pass this authorization step without `@`?

**Comment by ricellis** [comment]
>`@` seems to be necessary for this

Providing user information in the URLs within a replicator document is valid for CouchDB, but legacy and not recommended. The preferred approach is to use an `auth` block with the auth type, as you have done with `basic`.

I don't think having the `@` present is helping you, it's making CouchDB think there is some auth information in the URL (which there isn't).

* When you have `@`
    * the replication is failing because it can't resovle a host name when trying to do `_session` auth (`{conn_failed,{error,nxdomain}}`) and that host name doesn't exist so this makes sense).
* When you don't have `@`
    * the replication is failing because whatever creds are provided don't have permission for `couchdb_prod/dummy_prod` database

The case without `@` in the URL has progressed further.

AFAICT this is a credentials issue. The code above appears to use the same creds for both `couchdb_dev` and `couchdb_prod`. We know the creds are correct for `couchdb_dev` because they match what is being used to init the SDK and it has written the replication document successfully. Have you created the same username and password on `couchdb_prod` as well?

**Comment by raunakkbanerjee** [comment]
Yes I have created the same credentials for both couchdb instances using environment variables in the docker compose file.

**Comment by ricellis** [comment]
Good to hear you made some progress. It also confirms that this is unrelated to `cloudant-python-sdk` and is related to the database configuration. If you want assistance with CouchDB security models then these resources might be helpful:
* CouchDB documentation resources
    * [CouchDB `/{db}/_security`](https://docs.couchdb.org/en/stable/api/database/security.html)
        >Since CouchDB 3.x newly created databases have by default the `_admin` role to prevent unintentional access.
    * [CouchDB Authentication Database](https://docs.couchdb.org/en/stable/intro/security.html#authentication-database)
    * [CouchDB security and validation](https://docs.couchdb.org/en/stable/intro/overview.html#security-and-validation)
* [CouchDB chat (Slack/IRC)](https://couchdb.apache.org/#chat)
* [CouchDB users mailing list](https://couchdb.apache.org/#mailing-list)
* [CouchDB GitHub](https://github.com/apache/couchdb)

**Comment by raunakkbanerjee** [comment]
Hello @ricellis, I have assigned `_admin` role to myself to access the source database in `couchdb_prod` using,
```
names = ["admins"]
roles = ["_admin"]
admins = SecurityObject(names=names, roles=roles)
service_client.put_security(db="dummy_prod", admins=admins)
```
But as the target database doesn't exist yet (I want it to be created during replication), how do I make myself admin to be able to create a database in the `couchdb_dev` instance?
Right now, I have this error `{'error': 'unauthorized: unauthorized to access or create database http://couchdb_dev:5985/dummy_dev/'}`
